# Generated by Django 5.2.8 on 2025-11-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="activate",
            new_name="active",
        ),
    ]
